version: '3'
services:
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  test_database:
    image: "postgres"
    ports:
      - "5433:5432"
    env_file:
      - test_database.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql